blank_issues_enabled: true
contact_links:
  - name: Other Request
    url: https://www.ihe.net/about_ihe/contact_us/
    about: For all other requests
  - name: Other Public Comment form
    url: https://www.ihe.net/resources/public_comment/
    about: For submitting Public Comment without use of github Issue method
    