@startuml
hide footbox
allowmixing

object ":Organization" as Partners
Partners : name = "New Hope\nMedical Partners"

object ":Organization" as Valley
Valley : name = "Valley Access\nHealthcare"
Valley : OrgID = 1.2.3.2

object ":Organization" as OU
OU : name = "University Health"
OU : alias = "OU Health System",\n"OU Health"
OU : OrgID = 1.2.3.3

object ":Organization" as Urgent
Urgent : name = "Urgent Health"
Urgent : OrgID = 4.5.6.7

object ": Endpoint(s)" as vEndpoints
vEndpoints : connectionType = \n  PDQ-Supplier-Query,\n  XDS-Registry-Query,\n  XDS-Repository-Retrieve
Valley --> vEndpoints

object ": Endpoint(s)" as ouEndpoints
ouEndpoints : connectionType = \n  PDQ-Supplier-Query,\n  XDS-Registry-Query,\n  XDS-Repository-Retrieve
OU --> ouEndpoints

object ": Endpoint(s)" as uEndpoints
uEndpoints : connectionType = \n  PDQ-Supplier-Query,\n  XDS-Registry-Query,\n  XDS-Repository-Retrieve
Urgent --> uEndpoints

@enduml