@startuml
hide footbox

actor "Dr. Suwati" as actor1
participant "New Hope EHR" as ehr
participant "Valley Region\nHIE Directory" as dir
participant "Central PDQ\n: Endpoint" as xcpd
participant "Central XDS\n: Endpoint" as xca


actor1 -> ehr: Kick off search\ngiven known locations\nof treatment\n"Valley Access Healthcare",\n"OU Health"
ehr -> dir: Search Orgs for "Valley Access Healthcare",\n"OU Health" by name, alias
dir --> ehr: : Org 1.2.3.2, Org 1.2.3.3
note over ehr : Do they have Endpoints?\nNo, so see if they are in a doc sharing affiliation.

ehr -> dir: Check if each org is participatingOrganization\nof OrganizationAffiliation with code = "DocShare-federate-*"
dir --> ehr: : they are, .organization = Valley Region HIE\nand .code = DocShare-federate-int

ehr -> dir: Check OrganizationAffiliations for PDQ, XDS endpoints
dir --> ehr: : PDQ, XDS endpoints

note over ehr : Ok, these endpoints make info from these orgs\navailable to other members of the HIE.\nCan I access these endpoints as a member?
ehr -> dir: Check if New Hope is participatingOrganization\nof OrganizationAffiliation with .code = "HIEInitiator"\nand .organization = Valley Region HIE
dir --> ehr: : it is
ehr -> dir: Check if this OrganizationAffiliation points to the Endpoints I need
dir --> ehr: : it does

ehr -> xcpd : Match "Vanna Patterson"
xcpd --> ehr: : Match(es)

ehr -> xca : Get documents
xca --> ehr: : Documents, including from Urgent Health
ehr --> actor1: : Documents

@enduml