@startuml
hide footbox

object ":Organization" as hie
hie : name = "Valley Region HIE"
hie : OrgID = 1.2.3.0
hie : HCID = 1.2.3

object ":Endpoint" as xcpd
xcpd : connectionType = XCPD
object ":Endpoint" as xca
xca : connectionType = XCA Query,\nXCA Retrieve

object ":Organization" as Valley
Valley : name = "Valley Access Healthcare"
Valley : OrgID = 1.2.3.2

object ":Organization" as OU
OU : name = "University Health"
OU : alias = "OU Health System",\n"OU Health"
OU : OrgID = 1.2.3.3

object ":Organization" as Urgent
Urgent : name = "Urgent Health"
Urgent : OrgID = 4.5.6.7

object "orgAff1:OrganizationAffiliation" as OrgAff1
OrgAff1 : code = “HIE/HIO”, “XCPD-include”,\n“XCA-include”

OrgAff1 --> Valley : participatingOrganization
hie <-- OrgAff1 : organization

object "orgAff2:OrganizationAffiliation" as OrgAff2
OrgAff2 : code = “HIE/HIO”, “XCPD-include”,\n“XCA-include”

OrgAff2 --> OU : participatingOrganization
hie <-- OrgAff2 : organization

object "orgAff3:OrganizationAffiliation" as OrgAff3
OrgAff3 : code = “HIE/HIO”, “XCPD-include”,\n“XCA-include”

OrgAff3 --> Urgent : participatingOrganization
hie <-- OrgAff3 : organization

xcpd <- OrgAff1
xcpd <- OrgAff2
xcpd <- OrgAff3
OrgAff1 -> xca
OrgAff2 -> xca
OrgAff3 -> xca

@enduml