@startuml
hide footbox
allowmixing

object ":Organization" as Partners
Partners : name = "New Hope\nMedical Partners"

object "Seaside HIE" as hie2
hie2 : OrgID = 9.8.7.6
hie2 : HCID = 9.8.7
object ":Endpoint(s)" as sEndpoints
sEndpoints : connectionType = \n  PDQ-Supplier-Query,\n  XDS-Registry-Query,\n  XDS-Repository-Retrieve

object "Valley Region HIE" as hie
hie : name = "Valley Region HIE"
hie : OrgID = 1.2.3.0
hie : HCID = 1.2.3

object ":Organization" as Valley
Valley : name = "Valley Access\nHealthcare"
Valley : OrgID = 1.2.3.2

object ":Organization" as OU
OU : name = "University Health"
OU : alias = "OU Health System",\n"OU Health"
OU : OrgID = 1.2.3.3

object ":Organization" as Urgent
Urgent : name = "Urgent Health Valley"
Urgent : alias = "Urgent Health"
Urgent : OrgID = 4.5.6.7

object ":Organization" as UrgentNational
UrgentNational : name = "Urgent Health USA, LLC"
UrgentNational : alias = "Urgent Health"
UrgentNational : OrgID = 4.5.6
Urgent --> UrgentNational : partOf

object ":Organization" as Benefits
Benefits : name = "Valley Benefits"
Benefits : OrgID = 1.2.3.4

object ":OrganizationAffiliation" as OrgAff4
OrgAff4 --> Partners : participatingOrganization
hie <-- OrgAff4 : organization
OrgAff4 : code = “HIEInitiator”,\n"DocShare-federate-int"

object "Valley HIE Centralized Services : Endpoint(s)" as vEndpoints
vEndpoints : connectionType = \n  PDQ-Supplier-Query,\n  XDS-Registry-Query,\n  XDS-Repository-Retrieve

object ":OrganizationAffiliation" as OrgAff1
OrgAff1 : code = “HIEInitiator”,\n"DocShare-federate-int"
OrgAff1 --> Valley : participatingOrganization
hie <-- OrgAff1 : organization

object ":OrganizationAffiliation" as OrgAff2
OrgAff2 : code = “HIEInitiator”,\n"DocShare-federate-int"
OrgAff2 --> OU : participatingOrganization
hie <-- OrgAff2 : organization

object ":OrganizationAffiliation" as OrgAff3
OrgAff3 : code = “HIEInitiator”,\n"DocShare-federate-int"
OrgAff3 --> Urgent : participatingOrganization
hie <-- OrgAff3 : organization

object ":OrganizationAffiliation" as OrgAff5
OrgAff5 --> Benefits : participatingOrganization
OrgAff5 : code = “HIEInitiator”
hie <-- OrgAff5 : organization

OrgAff1 --> vEndpoints
OrgAff2 --> vEndpoints
OrgAff3 --> vEndpoints
OrgAff4 --> vEndpoints
OrgAff5 --> vEndpoints

object ":Organization" as SeasideHosp
SeasideHosp : name = "Seaside Hospital"
object ":OrganizationAffiliation" as OrgAff6
OrgAff6 --> SeasideHosp : participatingOrganization
OrgAff6 : code = “HIEInitiator”,\n"DocShare-federate-int"
hie2 <-- OrgAff6 : organization
OrgAff6 -> sEndpoints


@enduml