@startuml dir-endpoint-to-hybrid-org-structure
hide footbox

object "Organization I" as OrganizationI
OrganizationI : OrgID = 1.2.7
OrganizationI : HCID = 1.2.7
object "Organization J" as OrganizationJ
OrganizationJ : OrgID = 1.2.8
object "Endpoint" as EndpointI
EndpointI : address = https://orgI.org
object "Organization JA" as OrganizationJA
OrganizationJA : OrgID = 1.2.8.1
object "Organization JB" as OrganizationJB
OrganizationJB : OrgID = 1.2.8.2
object "Organization JC" as OrganizationJC
OrganizationJC : OrgID = 1.2.8.3
object ":OrganizationAffiliation" as OrgAff
OrgAff : code = DocShare-federate
OrgAff -> OrganizationJ : participatingOrganization
OrganizationI <-- OrgAff : organization

EndpointI <-- OrganizationI : endpoint

OrganizationJ <-- OrganizationJA : partOf
OrganizationJ <-- OrganizationJB : partOf
OrganizationJ <-- OrganizationJC : partOf

@enduml
