@startuml dir-org-specific-endpoint-from-affil
hide footbox

object "Organization G" as OrganizationG
OrganizationG : OrgID = 1.2.8
OrganizationG : HCID = 1.2.8
object "Affiliated Organization H" as OrganizationH
OrganizationH : OrgID = 1.3.4
object "OrganizationAffiliation" as OrgAff
OrgAff : code = DocShare-federate
object "Endpoint for G" as EndpointG
EndpointG : address = https://orgH.org/orgG

OrgAff --> OrganizationG : participatingOrganization
OrganizationH <-- OrgAff : organization
OrgAff -> EndpointG : endpoint
OrganizationH <- EndpointG : managingOrganization

@enduml
