@startuml mln-level-a-directory
hide footbox

object "Organization" as LNA
LNA : Name = "Lower Network A"
LNA : OrgID = 1.3
object "Endpoint" as EndpointA
EndpointA : address = https://lower_network_A.org
EndpointA <- LNA : endpoint
object "Organization" as HC7
HC7 : Name = "Community 1.2.7"
HC7 : HCID = 1.2.7
HC7 : OrgID = 1.2.7
object "Organization" as HC6
HC6 : Name = "Community 1.2.6"
HC6 : HCID = 1.2.6
HC6 : OrgID = 1.2.6

object ":OrganizationAffiliation" as OrgAff7
OrgAff7 : code = HIE/HIO
OrgAff7 -d-> HC7 : participatingOrganization
LNA <-- OrgAff7 : organization
object ":OrganizationAffiliation" as OrgAff6
OrgAff6 : code = HIE/HIO
OrgAff6 -d-> HC6 : participatingOrganization
LNA <-- OrgAff6 : organization

object "Endpoint" as Endpoint7
Endpoint7 : address = https://community_one_two_seven.org
Endpoint7 <- OrgAff7 : endpoint

object "Endpoint" as Endpoint6
Endpoint6 : address = https://community_one_two_six.org
Endpoint6 <- OrgAff6 : endpoint

object "Organization" as HC8
HC8 : Name = "Community 1.2.8"
HC8 : HCID =  1.2.8
HC8 : OrgID = 1.2.8

object ":OrganizationAffiliation" as OrgAff8
OrgAff8 : code = DocShare-federate
OrgAff8 -d-> HC8 : participatingOrganization
LNA <-u- OrgAff8 : organization

@enduml
